apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  serviceName: "cassandra"
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      initContainers:
      - name: init-cassandra
        image: cassandra:3.11
        command: ['sh', '-c', 'while ! cqlsh -e "DESCRIBE KEYSPACES"; do sleep 2; done; cqlsh -e "CREATE KEYSPACE IF NOT EXISTS my_keyspace WITH replication = {\'class\': \'SimpleStrategy\', \'replication_factor\': \'1\'};"']
      containers:
      - name: cassandra
        image: cassandra:3.11
        ports:
        - containerPort: 9042
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  ports:
    - port: 9042
      targetPort: 9042
  clusterIP: None
  selector:
    app: cassandra
