name: Setup Infrastructure and Deploy Cassandra

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: mini-net-428116
  REGION: us-central1
  ZONE: us-central1-a
  SQL_INSTANCE_NAME: mininet-sql-instance
  DB_NAME: mininet-db
  SQL_USERNAME: Birkbeck13924706
  SQL_PASSWORD: Birkbeck@13924706
  VM_NAME: cassandra-vm
  FIREWALL_RULE: allow-all
  SSH_PRIVATE_KEY_PATH: .ssh/gcp_key
  SSH_PUBLIC_KEY_PATH: .ssh/gcp_key.pub

jobs:
  setup-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth-gcp
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud config set compute/zone ${{ env.ZONE }}

      - name: Enable Cloud SQL Admin API
        run: |
          gcloud services enable sqladmin.googleapis.com

      - name: Enable Compute Engine API
        run: |
          gcloud services enable compute.googleapis.com

      - name: Enable Cloud Resource Manager API
        run: |
          gcloud services enable cloudresourcemanager.googleapis.com

      - name: Wait for API activation
        run: sleep 60

      - name: Check if SQL instance exists
        id: sql-instance-check
        run: |
          if gcloud sql instances describe ${{ env.SQL_INSTANCE_NAME }}; then
            echo "SQL instance already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "SQL instance does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create SQL instance
        if: steps.sql-instance-check.outputs.exists == 'false'
        run: |
          gcloud sql instances create ${{ env.SQL_INSTANCE_NAME }} \
            --database-version=MYSQL_8_0 \
            --tier=db-f1-micro \
            --region=${{ env.REGION }} \
            --root-password=root

      - name: Wait for SQL instance to be RUNNABLE
        run: |
          while [[ $(gcloud sql instances describe ${{ env.SQL_INSTANCE_NAME }} --format="value(state)") != "RUNNABLE" ]]; do
            echo "Waiting for SQL instance to be RUNNABLE..."
            sleep 10
          done
          echo "SQL instance is RUNNABLE."

      - name: Create SQL user
        run: |
          gcloud sql users create ${{ env.SQL_USERNAME }} --instance=${{ env.SQL_INSTANCE_NAME }} --password=${{ env.SQL_PASSWORD }}

      - name: Check if database exists
        id: db-check
        run: |
          if gcloud sql databases describe ${{ env.DB_NAME }} --instance=${{ env.SQL_INSTANCE_NAME }}; then
            echo "Database already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Database does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create SQL database
        if: steps.db-check.outputs.exists == 'false'
        run: |
          gcloud sql databases create ${{ env.DB_NAME }} --instance=${{ env.SQL_INSTANCE_NAME }}

  setup-cassandra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth-gcp
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud config set compute/zone ${{ env.ZONE }}

      - name: Check if VM exists
        id: vm-check
        run: |
          if gcloud compute instances describe ${{ env.VM_NAME }} --zone=${{ env.ZONE }}; then
            echo "VM already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "VM does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create VM for Cassandra
        if: steps.vm-check.outputs.exists == 'false'
        run: |
          gcloud compute instances create ${{ env.VM_NAME }} \
            --zone=${{ env.ZONE }} \
            --machine-type=e2-medium \
            --image=ubuntu-2004-focal-v20210720 \
            --image-project=ubuntu-os-cloud \
            --boot-disk-size=200GB \
            --tags=http-server,https-server

      - name: Wait for VM creation
        run: sleep 60

      - name: Check if firewall rule for SSH access via IAP exists
        id: firewall-rule-iap-check
        run: |
          if gcloud compute firewall-rules describe allow-ssh-ingress-from-iap; then
            echo "Firewall rule for SSH access via IAP already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Firewall rule for SSH access via IAP does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create firewall rule for SSH access via IAP
        if: steps.firewall-rule-iap-check.outputs.exists == 'false'
        run: |
          gcloud compute firewall-rules create allow-ssh-ingress-from-iap \
            --direction=INGRESS \
            --action=allow \
            --rules=tcp:22 \
            --source-ranges=35.235.240.0/20

      - name: Check if firewall rule for VM exists
        id: firewall-rule-check
        run: |
          if gcloud compute firewall-rules describe ${{ env.FIREWALL_RULE }}; then
            echo "Firewall rule for VM already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Firewall rule for VM does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create firewall rule for VM
        if: steps.firewall-rule-check.outputs.exists == 'false'
        run: |
          gcloud compute firewall-rules create ${{ env.FIREWALL_RULE }} \
            --direction=INGRESS \
            --priority=1000 \
            --network=default \
            --action=ALLOW \
            --rules=tcp:80,tcp:443,tcp:9042

      - name: Add SSH Key to VM
        run: |
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ${{ env.SSH_PRIVATE_KEY_PATH }}
          echo "${{ secrets.GCP_SSH_PUBLIC_KEY }}" > ${{ env.SSH_PUBLIC_KEY_PATH }}
          gcloud compute instances add-metadata ${{ env.VM_NAME }} \
            --metadata-from-file ssh-keys=${{ env.SSH_PUBLIC_KEY_PATH }}

      - name: Install Docker and create docker group
        run: |
          gcloud compute ssh ${{ env.VM_NAME }} --zone ${{ env.ZONE }} --ssh-key-file=${{ env.SSH_PRIVATE_KEY_PATH }} --command "
            sudo apt-get update;
            sudo apt-get install -y docker.io;
            sudo groupadd docker || true;
            sudo usermod -aG docker $USER;
            sudo systemctl restart docker"

      - name: SSH into VM and delete existing Cassandra containers
        run: |
          gcloud compute ssh ${{ env.VM_NAME }} --zone=${{ env.ZONE }} --ssh-key-file=${{ env.SSH_PRIVATE_KEY_PATH }} --command "
            echo 'Deleting existing Cassandra containers if they exist...';
            docker rm -f CassandraDB-1 || true"

      - name: SSH into VM and set up Cassandra
        run: |
          gcloud compute ssh ${{ env.VM_NAME }} --zone=${{ env.ZONE }} --ssh-key-file=${{ env.SSH_PRIVATE_KEY_PATH }} --command "
            echo 'Starting Docker and Cassandra setup...';
            echo 'Pulling Cassandra image...';
            docker run --name CassandraDB-1 -d -p 9042:9042 -p 7000:7000 -p 7001:7001 -p 7199:7199 cassandra:3.11;
            echo 'Waiting for CassandraDB-1 to start...';
            sleep 30;
            echo 'Cassandra container:';
            docker ps -a;
            echo 'Checking IP address for CassandraDB container...';
            docker inspect --format='{{ .NetworkSettings.IPAddress }}' CassandraDB-1;
            echo 'Checking nodetool status for CassandraDB-1...';
            docker exec -i -t CassandraDB-1 bash -c 'nodetool status'"
